### ISSUE TITLE
Ethnicity question

### ISSUE THREAD

**Issue by TamaraAdlin** [CoVital-Project/covital_dataset_builder#10]
What data do you need? If it's skin tone, ethnicity will not give you good data.  See attached image for a variety of options re: granularity for skin tones. UX can create a UI that's easy for the Dr. to use if we know the following:

1. Verify: the data you need for calibration is related to skin tone, not ethnicity per se, correct?
2. Verify: the skin tone that matters is the tone of the finger tip being tested, correct?
3. How much detail will help you? See image for swatch examples. 

![screenshot_01](https://user-images.githubusercontent.com/62766150/78612150-82ad4680-781d-11ea-8e38-9a11a5bffba0.jpg)

**Comment by MalcolmMielle** [comment]
@YoniSchirris you have suggested this data be collected so I guess you would have a better input than me on this question.

1. Yes it's related to skin color
2. Yes but I don't think it has to be extremely accurate,
3. That's an open question sadly :/

I think the idea is to see if we can find some features depending on skin color that would enable us to tune the network better. While it's true that ethnicity isn't the best marker for skin color, it seemed like the easiest to enter in a form. Other solutions, like taking a picture or asking for skin color, seemed too time consuming or confusing.

We also might just not end up using that information.

**Comment by TamaraAdlin** [comment]
It's actually easy to create a UI for this. We would simply have a scrolling series of swatches and as the doctor to choose the best match. I think it would be easier than ethnicity. And it can be as granular as would be helpful--could be five swatches up to over 80 as you can see in the examples, tho I'd recommend more like 10.

**Comment by MalcolmMielle** [comment]
Ok that's a good idea. I'm not sure how easily (and fast) I can do it but I'm going to have a look to see if it can be done :)

**Comment by YoniSchirris** [comment]
@TamaraAdlin Cool. Those swatches look great, and easy. I especially like the first example: VERY high-level.

Would you know if there's a "hand palm skin color" swatch? Since here we're not interested in the "normal" skin color, but the color of the hand palm / finger tips.

**Comment by LittlePea13** [comment]
We can't be sure if the final algorithm will use ethnicity or skin tone to help the predictions, but even if we do not use it for the models themselves, having the data available may help us validate that the models are not biased and work for any ethnicity.

**Comment by MalcolmMielle** [comment]
ok here is my proposal for the swatches:

![Screenshot_20200407-113345](https://user-images.githubusercontent.com/4457840/78654105-60bacf00-78c4-11ea-9e66-1c1315105832.png)

![Screenshot_20200407-113350](https://user-images.githubusercontent.com/4457840/78654116-644e5600-78c4-11ea-876f-99428adeec83.png)

The skin color is saved as an int that can be converted to an hexadecimal number to get the color. I've used the first color palette since it seemed to be the simplest one. Please confirm that this is working for everyone and I'll close the issue  :).

**Comment by MalcolmMielle** [comment]
Also there is redundant color in that screenshot that I have removed.

**Comment by YoniSchirris** [comment]
superb. fully agree with the implementation. Thanks

**Comment by MalcolmMielle** [comment]
Ok great. Closing for now but feel free to reopen if necessary :)

**Comment by TamaraAdlin** [comment]
Guys..I’m working on material design versions of each page for you to solve the usability issues that are still in the system. I will have them done in an hour or two. I think it’s easier than trying to tackle them one by one. I hope using Material Design will make it easy for you to implement the new UI elements across platforms. OK?

**Comment by MalcolmMielle** [comment]
Ok let's do that! Bear in mind I'm not an app developer at first so I'll do my best :)
