### ISSUE TITLE
Questions & Answers re health

### ISSUE THREAD

**Issue by TamaraAdlin** [CoVital-Project/covital_dataset_builder#11]
"Health" is a multi-select, and might need to be broken into two questions:

Existing health conditions
__. need list, but this would be multiselect

On immunosuppresant drugs?
__ either yes/no or yes /no with ability to name drugs.

If you can share the entire list of questions and answers, UX can quickly recommend UI changes to help.

**Comment by MalcolmMielle** [comment]
We are collecting data to train a model to estimate Spo2. I am not convinced that knowing the exact health condition of the person will help us train a better model for this purpose. 
For now, the idea behind knowing if the person is healthy, sick or recovering is for us to evaluate the algorithm against those markers:
* Is the algorithm working well for a sick person.
* Is it working well for a recovering person.
* Is it working well for a healthy person.

We do not plan to use that data to improve the model atm but we might.

Do immunosuppressants have an effect on the Spo2 level? I don't think we need to have the name of the drug to increase the accuracy of our model, that would be overfitting at that point.

**Comment by TamaraAdlin** [comment]
EXCELLENT. Then try this:

General health:
Healthy
Likely active COVID
Diagnosed active COVID
Recovering

**Comment by MalcolmMielle** [comment]
I think we don't want to targeting covid here. If the patient has something like the normal flu, we also want to do it. Our goal is to be able to estimate SpO2 for every sick person even if it's not covid.
I think adding the precision abut covid might confuse people who will not know what to answer if they have another sickness. What do you think?

**Comment by MalcolmMielle** [comment]
@YoniSchirris @LittlePea13 do you sick we need to have a distinction between likely active and diagnosed? I think it introduces a subjective classification that runs the risk of giving us bad labels (how do we determine if someone is likely sick VS actually sick)

**Comment by YoniSchirris** [comment]
I'd go for
- Not tested for COVID
- Tested positive COVID, active infection
- Tested postive COVID, recovering from COVID

We can then get the "likelihood" of COVID by mapping other symptoms and comorbidities to COVIDness.

**Comment by MalcolmMielle** [comment]
I think I understand what you mean, but I don't think I agree. keeping in mind that we're doing data collection only and not detection of Covid, from my point of view, we do not need to know about Covid at that stage and the fact that they are sick _with Covid_ is irrelevant for the problem we are trying to tackle. If we want to build a general dataset to validate SpO2 estimation algorithms, we need to not focus on one sickness only, even if the end result will be used for that sickness.

For example, let's say we record data from a patient with cancer. During the validation of our estimation method, we will want to know if we validate against sick patients, and that includes people with cancer. However, by having a question only concerned with knowing if they are sick _with Covid_, we reduce that subset, and have no way to know that a given subject suffered from a pretty serious illness. Even worse, it could add sick patients in our "not sick" subset of the dataset and we could miss out on the fact that our algorithm doesn't work we all sick patients.

**Comment by YoniSchirris** [comment]
True. I thought there was another field with "comorbidities" which had a much larger list, namely 

- Interstitial lung disease/sarcoidosis/idiopathic pulmonary fibrosis
- Lymphangioleiomyomatosis (LAM)
- Pulmonary vascular disease
- Cystic fibrosis
- Pulmonary hypertension
from https://github.com/CoVital-Project/pulse-ox-data-collection-web-service/issues/56

**Comment by MalcolmMielle** [comment]
I think that's targeted toward the final user facing app :)

**Comment by MalcolmMielle** [comment]
I'll close for nw and reopen if I get information that this is necessary
