### ISSUE TITLE
Pulse Oximeter device

### ISSUE THREAD

**Issue by TamaraAdlin** [CoVital-Project/covital_dataset_builder#12]
Should be 'brand' and 'model.'

Question: How critical is this info to the calibration process?

**Comment by MalcolmMielle** [comment]
I don't think that information is critical. it's nice to have it but I think it's one of the most optional field,

**Comment by TamaraAdlin** [comment]
OK. Might be worth verifying. If you do include the collection question, then it should be clearly marked optional, and I suggest the new layout / flow in the Ground Truth comment

**Comment by MalcolmMielle** [comment]
Ok I'll close this one since the discussion moved to another issue
