### ISSUE TITLE
Expand device brand and device reference to include specifics.

### ISSUE THREAD

**Issue by srivadi** [CoVital-Project/covital_dataset_builder#13]
It was confusing with respect to smartphone information versus oximeter info. Expand it to oximeter device brand and oximeter device reference.

**Comment by MalcolmMielle** [comment]
The new version of the app has a "SpO2 device" field name instead of simply saying "device". Does that sound good to you?

**Comment by srivadi** [comment]
Yes. Sounds good. :)
