### ISSUE TITLE
IOS Screen 1: Device

### ISSUE THREAD

**Issue by TamaraAdlin** [CoVital-Project/covital_dataset_builder#14]
Not clear that this is optional, or what specs you are referring to.

Also, this should come after the measurement, when the dr. is asked for the oximeter readings (not before taking the CoVital reading)

See additional comments on the "ground truth" issue card
![IMG_6940](https://user-images.githubusercontent.com/62766150/78613164-f3556280-781f-11ea-850f-16f9de467f5c.PNG)

**Comment by MalcolmMielle** [comment]
This page has been removed in the last versio of the app
