### ISSUE TITLE
Ios: Taking the video

### ISSUE THREAD

**Issue by TamaraAdlin** [CoVital-Project/covital_dataset_builder#15]
"Start recording" is cut off at the bottom of the screen and should be a large button, vs plain text.
Remove camera direction choice.
Note that when I used it, the 'countdown' to finishing recording restarted

**Comment by MalcolmMielle** [comment]
Just in case I misunderstood but the countdown is supposed to go off twice:
* The first time is a 10sec countdown to put the finger on the camera and be ready.
* Then it's a 30sec countdown where the video is recorded.
The label on the left side of the counter should explain what each counter is.

Is it what happened or the app showed another behavior?

**Comment by TamaraAdlin** [comment]
No. I couldn't reproduce the original issue I was seeing. But there are a couple of issues:
1. Cancel shouldn't be to the left of the label. It should be a button, if it's needed at all. If we detect the finger is gone, we should cancel and start again.
2. The recording timer is only 4 seconds.
3. The text and controls at the bottom of the screen are cut off. I recorded a video to show you.
[Uploading Covital IOS timer.mov.zip…]()

**Comment by MalcolmMielle** [comment]
Sorry fo the noose I'll open an issue for each of your suggestions.
