### ISSUE TITLE
Ground truth screen

### ISSUE THREAD

**Issue by TamaraAdlin** [CoVital-Project/covital_dataset_builder#16]
Suggest new structure and some bigger changes.

Move the SPO2 device info collection here, but in this order:

Patient Data
Age (Years)
Weight (KG)
Male / Female (this doesn't have to be a dropdown)
<ethnicity: open issue>

**Ground truth measurements**
SpO2 (%)
HR (BPM)
**SpO2 Device (optional)**
Brand
Model
(if possible, have dr. take a photo. we can get volunteers to look this up easily).
![IMG_6943](https://user-images.githubusercontent.com/62766150/78616010-e472ae00-7827-11ea-9294-cfe18f9f919e.PNG)

**Comment by MalcolmMielle** [comment]
Ok, should I move the "SpO2 device" in the same card as the ground truth measurements or in a separate one?

**Comment by MalcolmMielle** [comment]
I've made the male/female a radio button like this. What do you think in term usability? If you think it's better, i'l change the health section to also be radio buttons.

![Screenshot_20200407-121125](https://user-images.githubusercontent.com/4457840/78657549-38819f00-78c9-11ea-8907-ba5c70ded7bb.png)
