### ISSUE TITLE
IOS Submit confirm screen

### ISSUE THREAD

**Issue by TamaraAdlin** [CoVital-Project/covital_dataset_builder#17]
This is too strong. 
Do we need this?

Either way, the primary call to action should be Send (blue)
the gray button should be <Back.
![IMG_6945](https://user-images.githubusercontent.com/62766150/78616090-17b53d00-7828-11ea-943a-c39af6ca0d0f.PNG)

**Comment by MalcolmMielle** [comment]
I've removed that button in the last version and it sends directly mainly because the buttons were creating some anyone bugs. 

Now you directly clock and and there is no warning. I'll closer this issue but don't hesitate to answer here of you think that pop up was necessary
