### ISSUE TITLE
Text and control are cut off at the bottom of the screen

### ISSUE THREAD

**Issue by MalcolmMielle** [CoVital-Project/covital_dataset_builder#19]
The text and controls at the bottom of the screen are cut off. I recorded a video to show you. Reported by @TamaraAdlin. There is a video in Issue #15 

@vcapilladeveloper we might need to use a [SafeArea](https://api.flutter.dev/flutter/widgets/SafeArea-class.html) widget to protect the screen. Sadly I can't see the video so I'm not sure what the problem was.

**Comment by vcapilladeveloper** [comment]
I upload version 1.0.0(3) with this fixed.

**Comment by TamaraAdlin** [comment]
Malcom I’m about to send you a full set of designs using Material design components.
