### ISSUE TITLE
NEW WIREFRAMES for flow using material design elements

### ISSUE THREAD

**Issue by TamaraAdlin** [CoVital-Project/covital_dataset_builder#22]
Hi Guys. 
There were a bunch of usability issues in the designs. Instead of trying to describe all of them, the UX team and I redid the flow for you using Material Design, which means that the code for each of the UI elements already exists and is ready to use in Android and IOS. There are a couple of custom elements, but not many. These new UI widgets will solve most if not all of the usability concerns we have--and make it super easy for doctors to use the calibration tool. I know that it would have been better to have these much earlier but i hope they are still useful to you. Let me know what you think. Here's all the info, also posted in Slack: 

Hi All. UX has created wireframe designs for the 0.0 CALIBRATION tool. They are in Figma and use the Material Design elements. This means that you can also look up code information within the designs themselves (click “code” vs design or prototype in the right panel in figma). The file is set to let anyone view.
Link is here. Focus only on the Covid 0.0 Calibration page. [https://www.figma.com/file/XXzu9WgurGg308ZUkKOQ66/CoVital?node-id=23024%3A31416](https://www.figma.com/file/XXzu9WgurGg308ZUkKOQ66/CoVital?node-id=23024%3A31416)
Tutorial content still TBD but you’ll see a page/link for that.

Here's where to find what you need in Figma: 
![image](https://user-images.githubusercontent.com/62766150/78718567-5ce47800-78d7-11ea-8cd8-76d28d39e550.png)

**Comment by MalcolmMielle** [comment]
Still useful and probably easier to make those once you had a draft of the app in hands :).

**Comment by TamaraAdlin** [comment]
Absolutely!

**Comment by MalcolmMielle** [comment]
I'm trying to get as close to the wireframes as possible today. It's been super helpful so far but sadly I didn't manage to make the flutter export tool work. So I'm trying to get as close to the wireframe as possible.

I'm confused though as to why we need the medical history and status page. I'm not sure we need this information for the data pipeline atm. Especially, it seems too specific for Covid19 and not general enough for our purpose. It was already metnionned and referenced in #11. @YoniSchirris do you have any input. @dariodaprile Do you know anything about the data the Brasilian researcher were hoping to collect?

**Comment by MalcolmMielle** [comment]
Ok I've published a new version that I brought as close as possible (in one day) to the wireframe :). I'll close for now, but reopen if you think it's necessary
