### ISSUE TITLE
iOS v 1(4) forms not updated

### ISSUE THREAD

**Issue by dariodaprile** [CoVital-Project/covital_dataset_builder#28]
In IOS Txt is not updated...is there parity with Android? “Height” is not mentioned and “sick” is still present. 

Victor can Malcolm what do you think about having same versions in case of feature parity? All calibration app are v 0.X.X

Thx

**Comment by MalcolmMielle** [comment]
Both versions are be the same it's just that the iOS version hasn't been updated to the latest one while the Android one has been. 

At release, both version will be identical.
